#配置端口
server:
  port: 80

spring:
  #配置数据源
  datasource:
    #配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webstore?characterEncoding=utf-8&useSSL=false
    username: root
    password: Root@123


#MyBatis-Plus相关配置
mybatis-plus:
#  typeAliasesPackage: com.atguigu.mybatis_plus_demo
  mapper-locations: classpath*:com/atguigu/mybatis_plus_demo/mapper/*.xml
  configuration:
    #配置日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
